### ISSUE TITLE
Create function to fill in repo w/ OJO PDF report template

### ISSUE THREAD

**Issue by andrewjbe** [openjusticeok/ojoutils#2]
Should be able to use the function without looking up the `quarto` commands / URL and then doing it in the command line. `ojo_use_report_template()` or something should execute `quarto use template openjusticeok/ojo-report-template` in the proper directory.

**Comment by andrewjbe** [comment]
https://github.com/openjusticeok/ojo-report-template

**Comment by brancengregory** [comment]
Closed by #3
